// main_apps/angular11/src/app/angular11/angular11.component.ts
import { Component, OnInit } from '@angular/core';
import config from '../../config';

@Component({
  selector: 'app-angular11',
  templateUrl: './angular11.component.html',
  styleUrls: ['./angular11.component.sass']
})
export class Angular11Component implements OnInit {

  constructor() {}

  url = `${config.angular11}/child-angular11/`

  microAppData = {msg: '来自基座的数据'}

  ngOnInit (): void {
  }

  handleCreate (): void {
    console.log('child-angular11 创建了')
  }

  handleBeforeMount (): void {
    console.log('child-angular11 即将被渲染')
  }

  handleMount (): void {
    console.log('child-angular11 已经渲染完成')

    setTimeout(() => {
      this.microAppData = {msg: '来自基座的新数据'}
    }, 2000)
  }

  handleUnmount (): void {
    console.log('child-angular11 卸载了')
  }

  handleError (): void {
    console.log('child-angular11 加载出错了')
  }

  handleDataChange (e: CustomEvent): void {
    console.log('来自子应用 child-angular11 的数据:', e.detail.data)
  }
}

<div>
  <micro-app
    name='appname-angular11'
    [attr.url]='url'
    baseroute='/main-angular11/app-angular11'
    [data]='microAppData'
    (created)='handleCreate()'
    (beforemount)='handleBeforeMount()'
    (mounted)='handleMount()'
    (unmount)='handleUnmount()'
    (error)='handleError()'
    (datachange)='handleDataChange($event)'
  ></micro-app>
</div>

// main_apps/vite-vue3/src/views/angular11.vue
<template>
  <div>
    <micro-app
      name='appname-angular11'
      :url='url'
      baseroute='/main-vite/app-angular11'
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">
import 'zone.js'
import config from '../config'

export default {
  name: 'angular11',
  data () {
    return {
      url: `${config.angular11}/child/angular11/`,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-angular11 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-angular11 即将被渲染')
    },

    handleMount (): void {
      console.log('child-angular11 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-angular11 卸载了')
    },

    handleError (): void {
      console.log('child-angular11 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-angular11 的数据:', e.detail.data)
    },
  }
}
</script>
