// main_apps/react17/src/pages/nextjs11/nextjs11.tsx
/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
import { useState } from 'react'
import config from '../../config'

const Nextjs11 = () => {
  const [microAppData, changeMicroAppData] = useState({msg: '来自基座的数据'})

  function handleCreate () {
    console.log('child-nexjs 创建了')
  }

  function handleBeforeMount () {
    console.log('child-nexjs 即将被渲染')
  }

  function handleMount () {
    console.log('child-nexjs 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({msg: '来自基座的新数据'})
    }, 2000)
  }

  function handleUnmount () {
    console.log('child-nexjs 卸载了')
  }

  function handleError () {
    console.log('child-nexjs 加载出错了')
  }

  function handleDataChange (e: CustomEvent) {
    console.log('来自子应用 child-nexjs 的数据:', e.detail.data)
  }

  return (
    <div>
      <micro-app
        name='appname-nextjs11'
        url={`${config.nextjs11}/main-react17/app-nextjs11`}
        ssr
        disableScopecss
        data={microAppData}
        onCreated={handleCreate}
        onBeforemount={handleBeforeMount}
        onMounted={handleMount}
        onUnmount={handleUnmount}
        onError={handleError}
        onDataChange={handleDataChange}
      ></micro-app>
    </div>
  )
}

export default Nextjs11

// main_apps/vite-vue3/src/views/nextjs11.vue
<template>
  <div>
    <micro-app
      name='appname-nextjs11'
      :url='url'
      ssr
      disableScopecss
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">
import config from '../config'

export default {
  name: 'nextjs11',
  data () {
    return {
      url: `${config.nextjs11}/main-vite/app-nextjs11`,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-nextjs11 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-nextjs11 即将被渲染')
    },

    handleMount (): void {
      console.log('child-nextjs11 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-nextjs11 卸载了')
    },

    handleError (): void {
      console.log('child-nextjs11 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-nextjs11 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>
