// main_apps/react17/src/pages/nuxtjs/nuxtjs.tsx
/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
import { useState } from 'react'

const Nuxtjs = () => {
  const [microAppData, changeMicroAppData] = useState({msg: '来自基座的数据'})

  function handleCreate () {
    console.log('child-nuxjs 创建了')
  }

  function handleBeforeMount () {
    console.log('child-nuxjs 即将被渲染')
  }

  function handleMount () {
    console.log('child-nuxjs 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({msg: '来自基座的新数据'})
    }, 2000)
  }

  function handleUnmount () {
    console.log('child-nuxjs 卸载了')
  }

  function handleError () {
    console.log('child-nuxjs 加载出错了')
  }

  function handleDataChange (e: CustomEvent) {
    console.log('来自子应用 child-nuxjs 的数据:', e.detail.data)
  }

  return (
    <div>
      <micro-app
        name='appname-nuxtjs'
        url={'http://localhost:4003' + window.location.pathname}
        inline
        data={microAppData}
        onCreated={handleCreate}
        onBeforemount={handleBeforeMount}
        onMounted={handleMount}
        onUnmount={handleUnmount}
        onError={handleError}
        onDataChange={handleDataChange}
      ></micro-app>
    </div>
  )
}

export default Nuxtjs

// main_apps/vite-vue3/src/views/nuxtjs.vue
<template>
  <div>
    <micro-app
      name='appname-nuxtjs'
      :url='url'
      inline
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">

export default {
  name: 'nuxtjs',
  data () {
    return {
      url: 'http://localhost:4003' + location.pathname,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-nuxtjs 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-nuxtjs 即将被渲染')
    },

    handleMount (): void {
      console.log('child-nuxtjs 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-nuxtjs 卸载了')
    },

    handleError (): void {
      console.log('child-nuxtjs 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-nuxtjs 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>
