// main_apps/react17/src/pages/react16/react16.tsx
/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
import { useState } from 'react'

const React16 = () => {
  const [microAppData, changeMicroAppData] = useState({msg: '来自基座的数据'})

  function handleCreate () {
    console.log('child-react16 创建了')
  }

  function handleBeforeMount () {
    console.log('child-react16 即将被渲染')
  }

  function handleMount () {
    console.log('child-react16 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({msg: '来自基座的新数据'})
    }, 2000)
  }

  function handleUnmount () {
    console.log('child-react16 卸载了')
  }

  function handleError () {
    console.log('child-react16 加载出错了')
  }

  function handleDataChange (e: CustomEvent) {
    console.log('来自子应用 child-react16 的数据:', e.detail.data)
  }

  return (
    <div>
      <micro-app
        name='appname-react16'
        url='http://localhost:4004/'
        baseroute='/app-react16'
        data={microAppData}
        onCreated={handleCreate}
        onBeforemount={handleBeforeMount}
        onMounted={handleMount}
        onUnmount={handleUnmount}
        onError={handleError}
        onDataChange={handleDataChange}
      ></micro-app>
    </div>
  )
}

export default React16

// main_apps/vite-vue3/src/views/react16.vue
<template>
  <div>
    <micro-app
      name='appname-react16'
      url='http://localhost:4004/'
      baseroute='/app-react16'
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">

export default {
  name: 'react16',
  data () {
    return {
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-react16 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-react16 即将被渲染')
    },

    handleMount (): void {
      console.log('child-react16 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-react16 卸载了')
    },

    handleError (): void {
      console.log('child-react16 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-react16 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>
