// child_apps/vue2/src/pages/home.vue
<template>
  <div>
    <img alt="Vue logo" src="../assets/logo.png">
    <h1>子应用 -- Vue@{{version}}</h1>
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from '../components/HelloWorld.vue'
import Vue from 'vue'

export default {
  name: 'Home',
  data () {
    return {
      version: Vue.version,
    }
  },
  components: {
    HelloWorld
  },
}
</script>

<style>

</style>

// child_apps/react17/src/pages/home/home.tsx
import React from 'react';
import logo from '../../assets/logo.svg';
import './home.css';

function Home () {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          子应用123 -- react@{React.version}
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default Home;
