// main_apps/vue3/src/views/react17.vue
<template>
  <div>
    <micro-app
      name='appname-react17'
      url='http://localhost:4005/'
      baseroute='/app-react17'
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">

export default {
  name: 'react17',
  data() {
    return {
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-react17 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-react17 即将被渲染')
    },

    handleMount (): void {
      console.log('child-react17 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-react17 卸载了')
    },

    handleError (): void {
      console.log('child-react17 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-react17 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>

// main_apps/angular11/src/app/react17/react17.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-react17',
  templateUrl: './react17.component.html',
  styleUrls: ['./react17.component.sass']
})
export class React17Component implements OnInit {

  constructor() { }

  microAppData = {msg: '来自基座的数据'}

  ngOnInit (): void {
  }

  handleCreate (): void {
    console.log('child-react17 创建了')
  }

  handleBeforeMount (): void {
    console.log('child-react17 即将被渲染')
  }

  handleMount (): void {
    console.log('child-react17 已经渲染完成')

    setTimeout(() => {
      this.microAppData = {msg: '来自基座的新数据'}
    }, 2000)
  }

  handleUnmount (): void {
    console.log('child-react17 卸载了')
  }

  handleError (): void {
    console.log('child-react17 加载出错了')
  }

  handleDataChange (e: CustomEvent): void {
    console.log('来自子应用 child-react17 的数据:', e.detail.data)
  }

}

<div>
  <micro-app
    name='appname-react17'
    url='http://localhost:4005/'
    baseroute='/app-react17'
    [data]='microAppData'
    (created)='handleCreate()'
    (beforemount)='handleBeforeMount()'
    (mounted)='handleMount()'
    (unmount)='handleUnmount()'
    (error)='handleError()'
    (datachange)='handleDataChange($event)'
  ></micro-app>
</div>
