// child_apps/child-nuxtjs2/pages/page2.vue
<template>
  <div>
    <div id='public-links'>
      <NuxtLink to="/">Home</NuxtLink> |
      <NuxtLink to="/page2">Page2</NuxtLink>
    </div>
    <h3>page2</h3>
    <img src="/app-nuxtjs/micro-app-logo.png" width="100" alt="micro-app-logo" />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({})
</script>

// sub_apps/child-nextjs11/pages/page2.tsx
import type { NextPage } from 'next'
import styles from '../styles/page2.module.css'
import { formatPath } from '../lib/utils'

const Home: NextPage = () => {
  return (
    <div className={styles.page2Container}>
      <h3>page2</h3>
      <img src={formatPath("/micro-app-logo.png")} alt="micro-app-logo" />
    </div>
  )
}

export default Home
