// main_apps/react18/src/pages/angular11/angular11.tsx
/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
import { useState } from 'react'
import 'zone.js'
import config from '../../config'

const Angular11 = () => {
  const [microAppData, changeMicroAppData] = useState({msg: '来自基座的数据'})

  // zone.js冲突，created无法触发
  function handleCreate () {
    console.log('child-angular11 创建了')
  }

  function handleBeforeMount () {
    console.log('child-angular11 即将被渲染')
  }

  function handleMount () {
    console.log('child-angular11 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({msg: '来自基座的新数据'})
    }, 2000)
  }

  function handleUnmount () {
    console.log('child-angular11 卸载了')
  }

  function handleError () {
    console.log('child-angular11 加载出错了')
  }

  function handleDataChange (e: CustomEvent) {
    console.log('来自子应用 child-angular11 的数据:', e.detail.data)
  }

  return (
    <div>
      <micro-app
        name='angular11'
        url={`${config.angular11}/child/angular11/`}
        baseroute='/main-react18/app-angular11'
        router-mode="custom"
        data={microAppData}
        onCreated={handleCreate}
        onBeforemount={handleBeforeMount}
        onMounted={handleMount}
        onUnmount={handleUnmount}
        onError={handleError}
        onDataChange={handleDataChange}
      ></micro-app>
    </div>
  )
}

export default Angular11

// main_apps/vue2/src/pages/angular11.vue
<template>
  <div>
    <micro-app
      name='angular11'
      :url='url'
      router-mode='custom'
      baseroute='/main-vue2/app-angular11'
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script>
import 'zone.js'
import config from '../config'

export default {
  name: 'angular11',
  data () {
    return {
      url: `${config.angular11}/child/angular11/`,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate () {
      console.log('child-angular11 创建了')
    },

    handleBeforeMount () {
      console.log('child-angular11 即将被渲染')
    },

    handleMount () {
      console.log('child-angular11 已经渲染完成')

      setTimeout(() => {
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount () {
      console.log('child-angular11 卸载了')
    },

    handleError () {
      console.log('child-angular11 加载出错了')
    },

    handleDataChange (e) {
      console.log('来自子应用 child-angular11 的数据:', e.detail.data)
    },
  }
}
</script>
