// main_apps/vue2/src/pages/angular11.vue
<template>
  <div>
    <micro-app
      name='angular11'
      :url='url'
      router-mode='custom'
      baseroute='/main-vue2/app-angular11'
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script>
import 'zone.js'
import config from '../config'

export default {
  name: 'angular11',
  data () {
    return {
      url: `${config.angular11}/child/angular11/`,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate () {
      console.log('child-angular11 创建了')
    },

    handleBeforeMount () {
      console.log('child-angular11 即将被渲染')
    },

    handleMount () {
      console.log('child-angular11 已经渲染完成')

      setTimeout(() => {
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount () {
      console.log('child-angular11 卸载了')
    },

    handleError () {
      console.log('child-angular11 加载出错了')
    },

    handleDataChange (e) {
      console.log('来自子应用 child-angular11 的数据:', e.detail.data)
    },
  }
}
</script>

// main_apps/angular17/src/app/angular11/angular11.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, OnInit } from '@angular/core';
import config from '../../config';

@Component({
  selector: 'app-angular11',
  standalone: true,
  templateUrl: './angular11.component.html',
  styleUrls: ['./angular11.component.sass'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Angular11Component implements OnInit {

  constructor() {}

  url = `${config.angular11}/child/angular11/`

  microAppData = {msg: '来自基座的数据'}

  ngOnInit (): void {
  }

  handleCreate (): void {
    console.log('child-angular11 创建了')
  }

  handleBeforeMount (): void {
    console.log('child-angular11 即将被渲染')
  }

  handleMount (): void {
    console.log('child-angular11 已经渲染完成')

    setTimeout(() => {
      this.microAppData = {msg: '来自基座的新数据'}
    }, 2000)
  }

  handleUnmount (): void {
    console.log('child-angular11 卸载了')
  }

  handleError (): void {
    console.log('child-angular11 加载出错了')
  }

  handleDataChange (e: Event): void {
    if (e instanceof CustomEvent) {
      console.log('来自子应用 child-angular11 的数据:', e.detail.data)
    }
  }
}

<div>
  <micro-app
    name='angular11'
    [attr.url]='url'
    baseroute='/main-angular17/app-angular11'
    router-mode='custom'
    [data]='microAppData'
    (created)='handleCreate()'
    (beforemount)='handleBeforeMount()'
    (mounted)='handleMount()'
    (unmount)='handleUnmount()'
    (error)='handleError()'
    (datachange)='handleDataChange($event)'
  ></micro-app>
</div>
