// child_apps/child-react17/src/pages/page2/page2.tsx
import microAappLogo from '../../assets/micro-app-logo.png'
import './page2.css'

const Page2 = () => {
  return (
    <div>
      <h1>child-react17-page2</h1>
      <div className="child-react17-test-btn">test</div>
      <img src={microAappLogo} alt="micro-app-logo" />
    </div>
  )
}

export default Page2

// sub_apps/child-vite-vue3/src/views/page2.vue
<template>
  <div>
    <h4>page2</h4>
    <img :src="microAppLogo" alt="micro-app-logo" />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
const microAppLogo = new URL('../assets/micro-app-logo.png', import.meta.url)

export default defineComponent({
  name: 'Page2',
  data () {
    return {
      microAppLogo,
    }
  },
} as any)
</script>

<style>
</style>
