// main_apps/vue2/src/components/sidebar.vue
<template>
  <div id="sidebar">
    <h3 :abc="activeIndex">侧边栏</h3>
    <el-menu
      class="el-menu-vertical-demo"
      :default-active="activeIndex"
      @select="handleSelect"
      router
    >
      <el-menu-item index="/">
        <span slot="title" class='submenu-text'>首页</span>
      </el-menu-item>
      <!-- 菜单(el-submenu) index为子应用名称，子菜单(el-menu-item) index为路由地址 -->
      <el-submenu index="vue2">
        <template slot="title">
          <span class='submenu-text'>child-vue2</span>
        </template>
        <el-menu-item index="/app-vue2/">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-vue2/element-ui">
          <span class='menu-item-text'>element-ui</span>
        </el-menu-item>
        <el-menu-item index="/app-vue2/ant-design-vue">
          <span class='menu-item-text'>ant-design-vue</span>
        </el-menu-item>
      </el-submenu>
      <el-submenu index="vue3">
        <template slot="title">
          <span class='submenu-text'>child-vue3</span>
        </template>
        <el-menu-item index="/app-vue3">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-vue3/page2">
          <span class='menu-item-text'>page2</span>
        </el-menu-item>
      </el-submenu>
      <el-submenu index="vite">
        <template slot="title">
          <span class='submenu-text'>child-vite</span>
        </template>
        <el-menu-item index="/app-vite">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-vite#/page2">
          <span class='menu-item-text'>page2</span>
        </el-menu-item>
      </el-submenu>
      <el-submenu index="react16">
        <template slot="title">
          <span class='submenu-text'>child-react16</span>
        </template>
        <el-menu-item index="/app-react16">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-react16/ant-design">
          <span class='menu-item-text'>ant design</span>
        </el-menu-item>
      </el-submenu>
      <el-submenu index="react18">
        <template slot="title">
          <span class='submenu-text'>child-react18</span>
        </template>
        <el-menu-item index="/app-react18/">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-react18/ant-design">
          <span class='menu-item-text'>ant design</span>
        </el-menu-item>
      </el-submenu>
      <el-submenu index="angular11">
        <template slot="title">
          <span class='submenu-text'>child-angular11</span>
        </template>
        <el-menu-item index="/app-angular11">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-angular11/page2">
          <span class='menu-item-text'>page2</span>
        </el-menu-item>
      </el-submenu>
      <el-submenu index="nextjs11">
        <template slot="title">
          <span class='submenu-text'>child-nextjs11</span>
        </template>
        <el-menu-item index="/app-nextjs11">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-nextjs11/page2">
          <span class='menu-item-text'>page2</span>
        </el-menu-item>
      </el-submenu>
      <el-submenu index="nuxtjs2">/
        <template slot="title">
          <span class='submenu-text'>child-nuxtjs2</span>
        </template>
        <el-menu-item index="/app-nuxtjs2">
          <span class='menu-item-text'>home</span>
        </el-menu-item>
        <el-menu-item index="/app-nuxtjs2/page2">
          <span class='menu-item-text'>page2</span>
        </el-menu-item>
      </el-submenu>
    </el-menu>
  </div>
</template>

<script>
import microApp from '@micro-zoe/micro-app'

export default {
  name: 'App',
  data () {
    return {
      activeIndex: '/', // 当前激活菜单的 index
    }
  },
  created () {
    this.$router.onReady(() => {
      this.activeIndex = this.$route.path
    })
  },
  methods: {
    /**
     * 基座控制子应用跳转分为两个步骤：1、基座跳转 2、子应用跳转
     * 基座跳转后浏览器地址改变，此时子应用并不会响应浏览器的变化，需要主动控制子应用进行内部跳转
     */
    handleSelect (index, indexPath) {
      const appName = indexPath[0] // 获取子应用appName
      const childPath = '/main-vue2' + indexPath[1] // 子应用跳转地址为：基座前缀 + 跳转地址
      if (
        index !== '/' && // 非基座首页
        this.$route.path !== indexPath[1] && // 防止重复跳转
        microApp.getActiveApps().includes(appName) // 子应用活跃状态
      ) {
        /**
         * 基座跳转后浏览器url已经改变，但子应用并不会响应，需要使用microApp.router.replace控制子应用跳转
         * TODO: 优化路由跳转方式，去除异步操作异步执行是为了确保基座跳转后再控制子应用跳转
         */
        Promise.resolve().then(() => microApp.router.replace({
          name: appName,
          path: childPath,
        }))
      }
    },
  },
  watch: {
    $route () {
      this.activeIndex = this.$route.path
    }
  }
}
</script>

<style>
#sidebar {
  font-family: Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  display: inline-block;
  margin-right: 40px;
  border-right: 1px solid rgb(230, 230, 230);
}

#sidebar h4 {
  font-weight: revert;
}

#sidebar .el-menu-item {
  font-size: 16px;
}

#sidebar .el-menu {
  width: 200px;
  border-right: none;
}

#sidebar .submenu-text {
  font-size: 16px;
  font-weight: 500;
  user-select: none;
  color: #303133;
  font-family: "Helvetica Neue", tahoma, Arial, Verdana, "Microsoft YaHei", "宋体", sans-serif;
}

#sidebar .menu-item-text {
  font-size: 14px;
  user-select: none;
}
</style>

// main_apps/angular11/src/app/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { NestedTreeControl } from '@angular/cdk/tree';
import { MatTreeNestedDataSource } from '@angular/material/tree';
import { NavigationEnd, Router } from '@angular/router';
import microApp from '@micro-zoe/micro-app';

interface FoodNode {
  name?: string;
  key?: string;
  type?: string;
  children?: FoodNode[];
}

const sidebarItems: FoodNode[] = [
  { key: '/', name: '首页' },
  // 👇 一级菜单 key 为子应用名称，二级菜单 key 为路由地址
  { key: 'vue2', name: 'child-vue2', children: [
    { key: '/app-vue2', name: 'home' },
    { key: '/app-vue2/element-ui', name: 'element-ui' },
    { key: '/app-vue2/ant-design-vue', name: 'ant-design-vue' },
  ] },
  { key: 'vue3', name: 'child-vue3', children: [
    { key: '/app-vue3', name: 'home' },
    { key: '/app-vue3/page2', name: 'page2' },
  ] },
  { key: 'vite', name: 'child-vite', children: [
    { key: '/app-vite', name: 'home' },
    { key: '/app-vite#/page2', name: 'page2' },
  ] },
  { key: 'react16', name: 'child-react16', children: [
    { key: '/app-react16', name: 'home' },
    { key: '/app-react16/ant-design', name: 'ant design 4.x' },
  ] },
  { key: 'react18', name: 'child-react18', children: [
    { key: '/app-react18', name: 'home' },
    { key: '/app-react18/ant-design', name: 'ant design 5.x' },
  ] },
  { key: 'angular11', name: 'child-angular11', children: [
    { key: '/app-angular11', name: 'home' },
    { key: '/app-angular11/page2', name: 'page2' },
  ] },
  { key: 'nextjs11', name: 'child-nextjs11', children: [
    { key: '/app-nextjs11', name: 'home' },
    { key: '/app-nextjs11/page2', name: 'page2' },
  ] },
  { key: 'nuxtjs2', name: 'child-nuxtjs2', children: [
    { key: '/app-nuxtjs2', name: 'home' },
    { key: '/app-nuxtjs2/page2', name: 'page2' },
  ] },
];

const matchSidebarItemKeys = (key) => {
  const iter = (menus, keys) => {
    for (const menu of menus) {
      if (menu.key === key) {
        return [...keys, menu.key]
      }
      if (menu.children) {
        const res = iter(menu.children, [...keys, menu.key])
        if (res) {
          return res
        }
      }
    }
  }
  return iter(sidebarItems, [])
}

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.sass'],
})
export class SidebarComponent implements OnInit {
  treeControl = new NestedTreeControl<FoodNode>(node => node.children);
  dataSource = new MatTreeNestedDataSource<FoodNode>();
  currentRoute = '';

  constructor(router: Router) {
    /**
     * 用户点击菜单时控制基座应用、子应用跳转
     * 基座控制子应用跳转分为两个步骤：1、基座跳转 2、子应用跳转
     * 基座跳转后浏览器地址改变，此时子应用并不会响应浏览器的变化，需要主动控制子应用进行内部跳转
     */
    router.events.subscribe((e) => {
      if (!(e instanceof NavigationEnd)) {
        return;
      }
      if (this.currentRoute == e.url) {
        return;
      }
      const index = e.url;
      const indexPath = matchSidebarItemKeys(index);
      const currentPath = this.currentRoute;

      if (!indexPath) {
        return;
      }

      // 获取子应用appName
      const appName = indexPath[0];
      // 主应用跳转地址
      const mainPath = indexPath[indexPath.length - 1];
      // 子应用跳转地址需要补充前缀
      const childPath = '/main-angular11' + mainPath;
      // 👇 子应用切换路由
      if (
        index !== '/' && // 非基座首页
        currentPath !== mainPath && // 防止重复跳转
        microApp.getActiveApps().includes(appName) // 子应用活跃状态
      ) {
        /**
        * 基座跳转后浏览器url已经改变，但子应用并不会响应，需要使用microApp.router.replace控制子应用跳转
        * TODO: 优化路由跳转方式，去除异步操作异步执行是为了确保基座跳转后再控制子应用跳转
        */
        Promise.resolve().then(() => microApp.router.replace({
          name: appName,
          path: childPath,
        }));
      }
      this.treeControl.collapseAll();
      this.treeControl.expand(sidebarItems.find(s => s.key === indexPath[0]));
      this.currentRoute = index;
    });
    this.dataSource.data = sidebarItems;
  }

  hasChild = (_: number, node: FoodNode) => !!node.children && node.children.length > 0;

  ngOnInit(): void {
  }

}
