// main_apps/react17/src/pages/angular11/angular11.tsx
/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
import { useState } from 'react'
import 'zone.js'

const Angular11 = () => {
  const [microAppData, changeMicroAppData] = useState({msg: '来自基座的数据'})

  // zone.js冲突，created无法触发
  function handleCreate () {
    console.log('child-angular11 创建了')
  }

  function handleBeforeMount () {
    console.log('child-angular11 即将被渲染')
  }

  function handleMount () {
    console.log('child-angular11 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({msg: '来自基座的新数据'})
    }, 2000)
  }

  function handleUnmount () {
    console.log('child-angular11 卸载了')
  }

  function handleError () {
    console.log('child-angular11 加载出错了')
  }

  function handleDataChange (e: CustomEvent) {
    console.log('来自子应用 child-angular11 的数据:', e.detail.data)
  }

  return (
    <div>
      <micro-app
        name='appname-angular11'
        url='http://localhost:4001/'
        baseroute='/app-angular11'
        data={microAppData}
        onCreated={handleCreate}
        onBeforemount={handleBeforeMount}
        onMounted={handleMount}
        onUnmount={handleUnmount}
        onError={handleError}
        onDataChange={handleDataChange}
        destory
      ></micro-app>
    </div>
  )
}

export default Angular11

// main_apps/vue3/src/views/angular11.vue
<template>
  <div>
    <micro-app
      name='appname-angular11'
      url='http://localhost:4001/'
      baseroute='/app-angular11'
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">
import 'zone.js'

export default {
  name: 'angular11',
  data () {
    return {
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-angular11 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-angular11 即将被渲染')
    },

    handleMount (): void {
      console.log('child-angular11 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-angular11 卸载了')
    },

    handleError (): void {
      console.log('child-angular11 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-angular11 的数据:', e.detail.data)
    },
  }
}
</script>
