// main_apps/angular11/src/app/nextjs11/nextjs11.component.ts
import { Component, OnInit } from '@angular/core';
import config from '../../config';

@Component({
  selector: 'app-nextjs11',
  templateUrl: './nextjs11.component.html',
  styleUrls: ['./nextjs11.component.sass']
})
export class Nextjs11Component implements OnInit {

  constructor() {}

  url = `${config.nextjs11}/nextjs11`

  microAppData = {msg: '来自基座的数据'}

  ngOnInit (): void {
  }

  handleCreate (): void {
    console.log('child-nextjs11 创建了')
  }

  handleBeforeMount (): void {
    console.log('child-nextjs11 即将被渲染')
  }

  handleMount (): void {
    console.log('child-nextjs11 已经渲染完成')

    setTimeout(() => {
      this.microAppData = {msg: '来自基座的新数据'}
    }, 2000)
  }

  handleUnmount (): void {
    console.log('child-nextjs11 卸载了')
  }

  handleError (): void {
    console.log('child-nextjs11 加载出错了')
  }

  handleDataChange (e: CustomEvent): void {
    console.log('来自子应用 child-nextjs11 的数据:', e.detail.data)
  }
}

<div>
  <micro-app
    name='nextjs11'
    [attr.url]='url'
    ssr
    [data]='microAppData'
    (created)='handleCreate()'
    (beforemount)='handleBeforeMount()'
    (mounted)='handleMount()'
    (unmount)='handleUnmount()'
    (error)='handleError()'
    (datachange)='handleDataChange($event)'
  ></micro-app>
</div>

// main_apps/vue3/src/views/nextjs11.vue
<template>
  <div>
    <micro-app
      name='nextjs11'
      :url='url'
      ssr
      disableScopecss
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">
import config from '../config'

export default {
  name: 'nextjs11',
  data () {
    return {
      url: `${config.nextjs11}/nextjs11`,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-nextjs11 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-nextjs11 即将被渲染')
    },

    handleMount (): void {
      console.log('child-nextjs11 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-nextjs11 卸载了')
    },

    handleError (): void {
      console.log('child-nextjs11 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-nextjs11 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>
