// main_apps/react17/src/pages/nuxtjs2/nuxtjs2.tsx
/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
import { useState } from 'react'
import config from '../../config'

const Nuxtjs2 = () => {
  const [microAppData, changeMicroAppData] = useState({msg: '来自基座的数据'})

  function handleCreate () {
    console.log('child-nuxjs 创建了')
  }

  function handleBeforeMount () {
    console.log('child-nuxjs 即将被渲染')
  }

  function handleMount () {
    console.log('child-nuxjs 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({msg: '来自基座的新数据'})
    }, 2000)
  }

  function handleUnmount () {
    console.log('child-nuxjs 卸载了')
  }

  function handleError () {
    console.log('child-nuxjs 加载出错了')
  }

  function handleDataChange (e: CustomEvent) {
    console.log('来自子应用 child-nuxjs 的数据:', e.detail.data)
  }

  return (
    <div>
      <micro-app
        name='nuxtjs2'
        url={`${config.nuxtjs2}/nuxtjs2`}
        ssr
        data={microAppData}
        onCreated={handleCreate}
        onBeforemount={handleBeforeMount}
        onMounted={handleMount}
        onUnmount={handleUnmount}
        onError={handleError}
        onDataChange={handleDataChange}
      ></micro-app>
    </div>
  )
}

export default Nuxtjs2

// main_apps/vue3/src/views/nuxtjs2.vue
<template>
  <div>
    <micro-app
      name='nuxtjs2'
      :url='url'
      ssr
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">
import config from '../config'

export default {
  name: 'nuxtjs2',
  data () {
    return {
      url: `${config.nuxtjs2}/nuxtjs2`,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-nuxtjs2 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-nuxtjs2 即将被渲染')
    },

    handleMount (): void {
      console.log('child-nuxtjs2 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-nuxtjs2 卸载了')
    },

    handleError (): void {
      console.log('child-nuxtjs2 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-nuxtjs2 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>
