// main_apps/angular17/src/app/nuxtjs2/nuxtjs2.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, OnInit } from '@angular/core';
import config from '../../config';

@Component({
  selector: 'app-nuxtjs2',
  standalone: true,
  templateUrl: './nuxtjs2.component.html',
  styleUrls: ['./nuxtjs2.component.sass'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Nuxtjs2Component implements OnInit {

  constructor() { }

  url = `${config.nuxtjs2}/nuxtjs2`

  microAppData = {msg: '来自基座的数据'}

  ngOnInit (): void {
  }

  handleCreate (): void {
    console.log('child-nuxtjs2 创建了')
  }

  handleBeforeMount (): void {
    console.log('child-nuxtjs2 即将被渲染')
  }

  handleMount (): void {
    console.log('child-nuxtjs2 已经渲染完成')

    setTimeout(() => {
      this.microAppData = {msg: '来自基座的新数据'}
    }, 2000)
  }

  handleUnmount (): void {
    console.log('child-nuxtjs2 卸载了')
  }

  handleError (): void {
    console.log('child-nuxtjs2 加载出错了')
  }

  handleDataChange (e: Event): void {
    if (e instanceof CustomEvent) {
      console.log('来自子应用 child-nuxtjs2 的数据:', e.detail.data)
    }
  }

}

<div>
  <micro-app
    name='nuxtjs2'
    [attr.url]='url'
    ssr
    [data]='microAppData'
    (created)='handleCreate()'
    (beforemount)='handleBeforeMount()'
    (mounted)='handleMount()'
    (unmount)='handleUnmount()'
    (error)='handleError()'
    (datachange)='handleDataChange($event)'
  ></micro-app>
</div>

// main_apps/vue3/src/views/nuxtjs2.vue
<template>
  <div>
    <micro-app
      name='nuxtjs2'
      :url='url'
      ssr
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">
import config from '../config'

export default {
  name: 'nuxtjs2',
  data () {
    return {
      url: `${config.nuxtjs2}/nuxtjs2`,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-nuxtjs2 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-nuxtjs2 即将被渲染')
    },

    handleMount (): void {
      console.log('child-nuxtjs2 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-nuxtjs2 卸载了')
    },

    handleError (): void {
      console.log('child-nuxtjs2 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-nuxtjs2 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>
