// main_apps/angular11/src/app/nuxtjs/nuxtjs.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nuxtjs',
  templateUrl: './nuxtjs.component.html',
  styleUrls: ['./nuxtjs.component.sass']
})
export class NuxtjsComponent implements OnInit {

  constructor() { }

  url = 'http://localhost:4003' + location.pathname

  microAppData = {msg: '来自基座的数据'}

  ngOnInit (): void {
  }

  handleCreate (): void {
    console.log('child-nuxtjs 创建了')
  }

  handleBeforeMount (): void {
    console.log('child-nuxtjs 即将被渲染')
  }

  handleMount (): void {
    console.log('child-nuxtjs 已经渲染完成')

    setTimeout(() => {
      this.microAppData = {msg: '来自基座的新数据'}
    }, 2000)
  }

  handleUnmount (): void {
    console.log('child-nuxtjs 卸载了')
  }

  handleError (): void {
    console.log('child-nuxtjs 加载出错了')
  }

  handleDataChange (e: CustomEvent): void {
    console.log('来自子应用 child-nuxtjs 的数据:', e.detail.data)
  }

}

<div>
  <micro-app
    name='appname-nuxtjs'
    [attr.url]='url'
    [data]='microAppData'
    (created)='handleCreate()'
    (beforemount)='handleBeforeMount()'
    (mounted)='handleMount()'
    (unmount)='handleUnmount()'
    (error)='handleError()'
    (datachange)='handleDataChange($event)'
  ></micro-app>
</div>

// main_apps/vue3/src/views/nuxtjs.vue
<template>
  <div>
    <micro-app
      name='appname-nuxtjs'
      :url='url'
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">

export default {
  name: 'nuxtjs',
  data() {
    return {
      url: 'http://localhost:4003' + location.pathname,
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-nuxtjs 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-nuxtjs 即将被渲染')
    },

    handleMount (): void {
      console.log('child-nuxtjs 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-nuxtjs 卸载了')
    },

    handleError (): void {
      console.log('child-nuxtjs 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-nuxtjs 的数据:', e.detail.data)
    },
  }
} as any
</script>

<style>
</style>
