// main_apps/react17/src/pages/vite/vite.tsx
/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
import { useState } from 'react'
import { EventCenterForMicroApp } from '@micro-zoe/micro-app'

// @ts-ignore 因为vite子应用关闭了沙箱，我们需要为子应用appname-vite创建EventCenterForMicroApp对象来实现数据通信
window.eventCenterForAppNameVite = new EventCenterForMicroApp('appname-vite')

const Vite = () => {
  const [microAppData, changeMicroAppData] = useState({msg: '来自基座的数据'})

  function handleCreate () {
    console.log('child-vite 创建了')
  }

  function handleBeforeMount () {
    console.log('child-vite 即将被渲染')
  }

  function handleMount () {
    console.log('child-vite 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({msg: '来自基座的新数据'})
    }, 2000)
  }

  function handleUnmount () {
    console.log('child-vite 卸载了')
  }

  function handleError () {
    console.log('child-vite 加载出错了')
  }

  function handleDataChange (e: CustomEvent) {
    console.log('来自子应用 child-vite 的数据:', e.detail.data)
  }

  return (
    <div>
      <micro-app
        name='appname-vite'
        url='http://localhost:4007/'
        inline
        disablesandbox
        data={microAppData}
        onCreated={handleCreate}
        onBeforemount={handleBeforeMount}
        onMounted={handleMount}
        onUnmount={handleUnmount}
        onError={handleError}
        onDataChange={handleDataChange}
      ></micro-app>
    </div>
  )
}

export default Vite

// main_apps/vue3/src/views/vite.vue
<template>
  <div>
    <micro-app
      name='appname-vite'
      url='http://localhost:4007/'
      inline
      disablesandbox
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

<script lang="ts">
import { EventCenterForMicroApp } from '@micro-zoe/micro-app'

// @ts-ignore 因为vite子应用关闭了沙箱，我们需要为子应用appname-vite创建EventCenterForMicroApp对象来实现数据通信
window.eventCenterForAppNameVite = new EventCenterForMicroApp('appname-vite')

export default {
  name: 'vite',
  data () {
    return {
      microAppData: {msg: '来自基座的数据'}
    }
  },
  methods: {
    handleCreate (): void {
      console.log('child-vite 创建了')
    },

    handleBeforeMount (): void {
      console.log('child-vite 即将被渲染')
    },

    handleMount (): void {
      console.log('child-vite 已经渲染完成')

      setTimeout(() => {
        // @ts-ignore
        this.microAppData = {msg: '来自基座的新数据'}
      }, 2000)
    },

    handleUnmount (): void {
      console.log('child-vite 卸载了')
    },

    handleError (): void {
      console.log('child-vite 加载出错了')
    },

    handleDataChange (e: CustomEvent): void {
      console.log('来自子应用 child-vite 的数据:', e.detail.data)
    },
  }
}
</script>

<style>
</style>
