// child_apps/vue3/src/views/home.vue
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <HelloWorld :msg="'子应用 -- Vue@'+version"/>
  </div>
</template>

<script lang="ts">
import { defineComponent, version } from 'vue'
import HelloWorld from '@/components/HelloWorld.vue' // @ is an alias to /src

export default defineComponent({
  name: 'Home',
  data () {
    return {
      version,
    }
  },
  components: {
    HelloWorld
  }
})
</script>

// child_apps/child-react17/src/pages/home/home.tsx
import React from 'react';
import logo from '../../assets/logo.svg';
import './home.css';

function Home () {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          子应用 -- react@{React.version}
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default Home;
