// child_apps/vite-vue3/src/views/home.vue
<template>
  <div>
    <img alt="Vue logo" :src="logoPath" />
    <HelloWorld :msg="'子应用 -- Vite+Vue@'+version" />
  </div>
</template>

<script lang="ts">
import { defineComponent, version } from 'vue'
import HelloWorld from '../components/HelloWorld.vue'
const logoPath = new URL('../assets/logo.png', import.meta.url).href

export default defineComponent({
  name: 'Home',
  setup () {
    return { logoPath, version }
  },
  components: {
    HelloWorld
  }
})
</script>

<style>

</style>

// child_apps/child-react17/src/pages/home/home.tsx
import React from 'react';
import logo from '../../assets/logo.svg';
import './home.css';

function Home () {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          子应用 -- react@{React.version}
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default Home;
